import { Footer, Navbar } from "@/components";
import { ModalOpenContextProvider } from "@/context/modal.context";
import { FilterProductsContextProvider } from "@/context/filterProduct.context";
import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";

const roboto = Barlow({
  weight: ["100","200","300","400","500","600","700","800","900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <body className={roboto.className}>
        <Navbar />
        <FilterProductsContextProvider>
        <ModalOpenContextProvider>{children}</ModalOpenContextProvider>
        </FilterProductsContextProvider>
        <Footer />
      </body>
    </html>
  );
}
