export const envs = {
  MAILER_SERVICE: process.env.MAILER_SERVICE!,
  MAILER_EMAIL: process.env.MAILER_EMAIL!,
  MAILER_SECRET_KEY: process.env.MAILER_SECRET_KEY!,
  MAILER_RECEPTOR:process.env.MAILER_RECEPTOR!,
  DOMAIN: process.env.NEXT_PUBLIC_DOMAIN!,
  API_DOMAIN:process.env.NEXT_PUBLIC_API_DOMAIN!
};

